api/urls.py
from django.urls import path

from api import views

# app_name = 'api'

urlpatterns = [
    path('hello/', views.HelloWorld.as_view(), name='hello'),
    path('login/', views.LoginAPIView.as_view(), name='login'),
    path('register/', views.register_user, name='register'),
     path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    # path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    # path('lougout/', views.LogoutAPIView.as_view(), name='logout'),
]

authentification/urls.py
from django.urls import path
from . import views

app_name = 'authentification'

urlpatterns = [
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register, name='register'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
]

config/urls.py
"""config URL Configuration"""
from django.contrib import admin
from django.urls import include, path

# from config import settings
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('auth/', include('authentification.urls')),
    path('api/', include('api.urls')),
]

# if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

# Create your views here.

def home(request):
    
    return render(request, 'home/index.html')

home/templates/home/index.html
{% extends 'base.html' %}


{% block title %}
    Accueil
{% endblock title %}
    

{% block content %}
    <h1>Accueil</h1>

    


    
    {% if user.is_authenticated %}
        <h4>Bonjour {{ user.username }}</h4>
        <h4>mail {{ user.email }}</h4>
        <a class="btn btn-primary btn-lg " href="{% url 'authentification:logout' %}">Se deconnecter</a>
    {% else %}
        <h4>Bonjour anonyme</h4>
        <a class="btn btn-primary btn-lg " href="{% url 'authentification:login' %}">Se connecter</a>
        <a class="btn btn-primary btn-lg " href="{% url 'authentification:register' %}">S'enregistrer</a>
    {% endif %}
        


    
{% endblock content %}
    